version: "3.7"
services:
  spark-master:
    image: spark-master:2.3.1
    container_name: spark-master
    hostname: spark-master
    #ports: #bind port 8080 to access cluster master UI, bind port 7077 to submit jobs from outside the cluster
    #  - "10084:8080" 
    #  - "7077:7077"
    networks: 
      spark-network:
        ipv4_address: 10.5.0.2
    volumes:
       - input-volume:/spark-data
    environment:
      - "SPARK_LOCAL_IP=spark-master"
  
  spark-submit:
    image: spark-submit:2.3.1
    container_name: spark-submit
    hostname: spark-submit
    depends_on:
      - spark-master
    ports: #bind port 8080 to expose REST API for text similarity calculation
      - "12321:8080"
    environment:
      - "SPARK_LOCAL_IP=spark-submit"
    volumes:
       - input-volume:/spark-data
    networks: 
      spark-network:
        ipv4_address: 10.5.0.6
  
  spark-worker-1:
    image: spark-worker:2.3.1
    container_name: spark-worker-1
    hostname: spark-worker-1
    #ports: #bind port 8081 to access cluster worker UI
    #  - "8081:8081" 
    depends_on:
      - spark-master
    env_file: ./env/spark-worker.sh
    environment:
      - "SPARK_LOCAL_IP=spark-worker-1"
    networks: 
      spark-network:
        ipv4_address: 10.5.0.3
    volumes:
       - input-volume:/spark-data
  
  spark-worker-2:
    image: spark-worker:2.3.1
    container_name: spark-worker-2
    hostname: spark-worker-2
    #ports: #bind port 8081 to access cluster worker UI
    #  - "8081:8081" 
    depends_on:
      - spark-master
    env_file: ./env/spark-worker.sh
    environment:
      - "SPARK_LOCAL_IP=spark-worker-2"
    networks: 
      spark-network:
        ipv4_address: 10.5.0.4
    volumes:
       - input-volume:/spark-data

  spark-worker-3:
    image: spark-worker:2.3.1
    container_name: spark-worker-3
    hostname: spark-worker-3
    #ports: #bind port 8081 to access cluster worker UI
    #  - "8081:8081" 
    depends_on:
      - spark-master
    env_file: ./env/spark-worker.sh
    environment:
      - "SPARK_LOCAL_IP=spark-worker-3"
    networks: 
      spark-network:
        ipv4_address: 10.5.0.5
    volumes:
       - input-volume:/spark-data
networks:
  spark-network:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 10.5.0.0/16
volumes:
  input-volume:
